version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=vedu_test
      - POSTGRES_PASSWORD=vedansh@25
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:

#docker-compose.yaml file is the way of tellin gdocker how to run a specific image